name: Build and Push to Public ECR

on:
  push:
    branches: [ "main" ]
    paths:
      # - "esgarn-backend/**"
      - "go-backend/**"

env:
  AWS_REGION: us-east-1  # Public ECR auth only works in us-east-1

jobs:
  build-and-push-ESGARN:
    name: Build & Push ESGARN Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}  # Must be us-east-1

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build and Push Image
        run: |
          docker build -t ${{ secrets.ECR_REPO_ESRGAN }} ./esgarn-backend
          docker push ${{ secrets.ECR_REPO_ESRGAN }}

  build-and-push-go:
    name: Build & Push Go Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}  # Must be us-east-1

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build and Push Image
        run: |
          docker build -t ${{ secrets.ECR_REPO_GO }} ./go-backend
          docker push ${{ secrets.ECR_REPO_GO }}